---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed on Debian.
  apt: "name={{ item }} state={{ apache_packages_state }}"
  with_items: "{{ apache_packages }}"

- name: "Change user to run Apache under to: '{{ apache_user }}'"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export APACHE_RUN_USER='
    line: 'export APACHE_RUN_USER={{ apache_user }}'
  when: "apache_user != 'www-data'"

- name: "Change group to run Apache under to: '{{ apache_group }}'"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export APACHE_RUN_USER='
    line: 'export APACHE_RUN_USER={{ apache_group }}'
  when: "apache_group != 'www-data'"
